baseURL = "https://quizmathgenius.com/"
languageCode = "en-us"
title = "Math Learning Site"

theme = "hextra"

[params]
  defaultTheme = "light"
  displayToggle = true
  customCSS = ["css/custom.css"]
  sidebar = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["$$","$$"], ["\\[","\\]"]]
          inline = [["$","$"], ["\\(","\\)"]]

