baseURL = "https://quizmathgenius.com/"
languageCode = "en-us"
title = "Math Learning Site"

theme = "hextra"

[services]
  [services.googleAnalytics]
    ID = "G-SBWP5KZB8K"

[params]
  defaultTheme = "light"
  displayToggle = false
  sidebar = true

  [params.navbar]
    [params.navbar.logo]
      link = "/"

  [params.search]
    enable = false
    index = "title"

  [params.footer]
    displayPoweredBy = false
    displayCopyright = false

[[menu.main]]
  name = "Practice Hub"
  pageRef = "/algebra-i/linear-algebra/practice-questions"
  weight = 1

[[menu.main]]
  name = "Blogs"
  pageRef = "/blog"
  weight = 2

[[menu.main]]
  name = "Diagnostic Q&A"
  pageRef = "/algebra-i/factoring-trinomials/practice-questions/factoring-trinomials"
  weight = 3
  [menu.main.params]
    style = "cta"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["$$","$$"], ["\\[","\\]"]]
          inline = [["$","$"], ["\\(","\\)"]]
