baseURL = "https://quizmathgenius.com/"
languageCode = "en-us"
title = "Math Learning Site"

theme = "hextra"

[params]
  defaultTheme = "light"
  displayToggle = true
  customCSS = ["css/custom.css"]